---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Sekce
- type: directory
  path: content/sections
  label: Sekce webu
  create: all
  match: "**/*"
- type: document
  path: content/main.md
  label: Obsah
- type: document
  path: content/about.md
  label: O firmě
- type: document
  path: content/galerie.md
  label: Galerie
  match: "**/*"
upload_dir: assets/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
